// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/flows": {
            "get": {
                "description": "Retrieve a list of all flows",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Get all flows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new flow by providing flow details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Create a new flow",
                "parameters": [
                    {
                        "description": "Flow Data",
                        "name": "flow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/flows/{id}": {
            "get": {
                "description": "Retrieve details of a specific flow by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Get flow details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing flow by providing its ID and updated details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Update a flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Flow Data",
                        "name": "flow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a specific flow by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Delete a flow by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/flows/{id}/execute": {
            "post": {
                "description": "Execute a specific flow by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flows"
                ],
                "summary": "Execute a flow by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.FlowDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/integrations": {
            "get": {
                "description": "Get a list of all integrations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "List all integrations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationResponseDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new integration with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "Create a new integration",
                "parameters": [
                    {
                        "description": "Integration data",
                        "name": "integration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        },
        "/integrations/{id}": {
            "get": {
                "description": "Retrieve details of a specific integration by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "Get a specific integration by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Integration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the details of an existing integration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "Update an existing integration by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Integration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated integration data",
                        "name": "integration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_application_dto.IntegrationResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a specific integration by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "Delete an integration by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Integration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "generic-integration-platform_internal_application_dto.EndpointRequestDTO": {
            "type": "object",
            "required": [
                "method",
                "name",
                "path"
            ],
            "properties": {
                "headers": {
                    "description": "Additional headers (optional)",
                    "type": "string"
                },
                "method": {
                    "description": "HTTP method (e.g., GET, POST)",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the endpoint",
                    "type": "string"
                },
                "path": {
                    "description": "Path of the endpoint",
                    "type": "string"
                }
            }
        },
        "generic-integration-platform_internal_application_dto.EndpointResponseDTO": {
            "type": "object",
            "properties": {
                "method": {
                    "description": "HTTP method (e.g., GET, POST)",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the endpoint",
                    "type": "string"
                },
                "path": {
                    "description": "Path of the endpoint",
                    "type": "string"
                }
            }
        },
        "generic-integration-platform_internal_application_dto.FlowDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier for the flow",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the flow",
                    "type": "string"
                },
                "steps": {
                    "description": "List of steps in the flow",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/generic-integration-platform_internal_application_dto.StepDTO"
                    }
                }
            }
        },
        "generic-integration-platform_internal_application_dto.IntegrationRequestDTO": {
            "type": "object",
            "required": [
                "base_url",
                "currency",
                "endpoints",
                "name",
                "type"
            ],
            "properties": {
                "auth_token": {
                    "description": "The authentication token (optional)",
                    "type": "string"
                },
                "auth_type": {
                    "description": "Type of authentication (e.g., Bearer, Basic)",
                    "type": "string"
                },
                "base_url": {
                    "description": "Base URL for API requests",
                    "type": "string"
                },
                "currency": {
                    "description": "Currency for transactions",
                    "type": "string"
                },
                "endpoints": {
                    "description": "List of endpoints associated with this integration",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/generic-integration-platform_internal_application_dto.EndpointRequestDTO"
                    }
                },
                "name": {
                    "description": "Name of the integration",
                    "type": "string"
                },
                "type": {
                    "description": "Type of integration (e.g., REST, gRPC)",
                    "type": "string"
                }
            }
        },
        "generic-integration-platform_internal_application_dto.IntegrationResponseDTO": {
            "type": "object",
            "properties": {
                "auth_type": {
                    "description": "Type of authentication (e.g., Bearer, Basic)",
                    "type": "string"
                },
                "base_url": {
                    "description": "Base URL for API requests",
                    "type": "string"
                },
                "currency": {
                    "description": "Currency for transactions",
                    "type": "string"
                },
                "endpoints": {
                    "description": "List of endpoints associated with this integration",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/generic-integration-platform_internal_application_dto.EndpointResponseDTO"
                    }
                },
                "id": {
                    "description": "Unique identifier for the integration",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the integration",
                    "type": "string"
                },
                "type": {
                    "description": "Type of integration (e.g., REST, gRPC)",
                    "type": "string"
                }
            }
        },
        "generic-integration-platform_internal_application_dto.StepDTO": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action to be performed in the step",
                    "type": "string"
                },
                "integration_id": {
                    "description": "ID of the associated integration",
                    "type": "string"
                },
                "params": {
                    "description": "Parameters for the step",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "generic-integration-platform_internal_infra_http_dto.ErrorResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Error message to describe the issue",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "To access protected routes, add the x-api-key header with your API key. Example: \"x-api-key: your-api-key\"",
            "type": "apiKey",
            "name": "x-api-key",
            "in": "header"
        }
    },
    "security": [
        {
            "ApiKeyAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Generic Integration Platform API",
	Description:      "This is an Generic Integration Platform API that processes multiple integration and integration flows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
