definitions:
  agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO:
    properties:
      message:
        type: string
    type: object
  agnostic-payment-platform_internal_application_merchant_dto.LoginRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  agnostic-payment-platform_internal_application_merchant_dto.LoginResponseDTO:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  agnostic-payment-platform_internal_application_merchant_dto.SignupRequestDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  agnostic-payment-platform_internal_application_merchant_dto.SuccessResponseDTO:
    properties:
      message:
        type: string
    type: object
  agnostic-payment-platform_internal_application_payment_dto.PaymentDetailsDTO:
    properties:
      amount:
        example: 12.45
        type: number
      created_at:
        type: string
      currency:
        example: USD
        type: string
      id:
        example: uuid123421
        type: string
      merchant_id:
        example: uuidasfhtu12
        type: string
      payment_status:
        type: string
      refunded_amount:
        type: number
    type: object
  agnostic-payment-platform_internal_application_payment_dto.PaymentRequestDTO:
    properties:
      amount:
        type: number
      card_number:
        type: string
      currency:
        type: string
      cvv:
        type: string
      expiry_date:
        type: string
      merchant_id:
        type: string
      type:
        type: string
    required:
    - amount
    - card_number
    - currency
    - cvv
    - expiry_date
    - merchant_id
    - type
    type: object
  agnostic-payment-platform_internal_application_payment_dto.PaymentResponseDTO:
    properties:
      amount:
        type: number
      currency:
        type: string
      message:
        type: string
      payment_id:
        type: string
      payment_status:
        type: string
      transaction_id:
        type: string
    required:
    - transaction_id
    type: object
  agnostic-payment-platform_internal_application_payment_dto.RefundDTO:
    properties:
      amount:
        type: number
      payment_id:
        type: string
      reason:
        type: string
      transaction_id:
        type: string
    required:
    - amount
    - payment_id
    - transaction_id
    type: object
  gin.H:
    additionalProperties: {}
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an agnostic payment platform API that processes and retrieves
    payment details.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Agnostic Payment Platform API
  version: "1.0"
paths:
  /merchant/login:
    post:
      consumes:
      - application/json
      description: Login a merchant with an email and password.
      parameters:
      - description: Login request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.LoginRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.LoginResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO'
      summary: Login as a merchant
      tags:
      - Merchants
  /merchant/signup:
    post:
      consumes:
      - application/json
      description: Register a new merchant with an email, password, and name.
      parameters:
      - description: Signup request
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.SignupRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.SuccessResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_merchant_dto.ErrorResponseDTO'
      summary: Register a new merchant
      tags:
      - Merchants
  /payments:
    post:
      consumes:
      - application/json
      description: Processes a payment based on the provided details
      parameters:
      - description: Payment Request
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/agnostic-payment-platform_internal_application_payment_dto.PaymentRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_payment_dto.PaymentResponseDTO'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Unable to process payment
          schema:
            $ref: '#/definitions/gin.H'
      summary: Process a payment
      tags:
      - payments
  /payments/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves details of a payment by its ID
      parameters:
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_payment_dto.PaymentDetailsDTO'
        "400":
          description: Missing payment ID
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Payment not found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Unable to retrieve payment details
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get payment details
      tags:
      - payments
  /payments/refund:
    post:
      consumes:
      - application/json
      description: Handles the refund request by extracting refund details from the
        request body and processing the refund.
      parameters:
      - description: Refund details
        in: body
        name: refundDTO
        required: true
        schema:
          $ref: '#/definitions/agnostic-payment-platform_internal_application_payment_dto.RefundDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Refund processed successfully
          schema:
            $ref: '#/definitions/agnostic-payment-platform_internal_application_payment_dto.PaymentResponseDTO'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Unable to process payment
          schema:
            $ref: '#/definitions/gin.H'
      summary: Process a refund request
      tags:
      - payments
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    description: 'To access protected routes, add the x-api-key header with your API
      key. Example: "x-api-key: your-api-key"'
    in: header
    name: x-api-key
    type: apiKey
swagger: "2.0"
